version: "3.9"
services:
  
  frontend:
    env_file:
      - ./.env
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80
      - 49153:49153
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    restart: always

  backend:
    env_file:
      - ./.env
    depends_on:
      - mysql
    build: backend
    ports:
      - 3000:3000
    container_name: backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    restart: always
    links:
      - mysql

  mysql:
    env_file:
      - ./.env
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cobros
    ports:
      - 3309:3306
    volumes:
      - ./mysql:/var/lib/mysql
    
    